myblog/blog/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'blog'

urlpatterns = [
    path('',views.PostListView.as_view(), name="post_list" ),
    path('about/', views.AboutView.as_view(), name="about"),
    path('post/new',views.PostCreateView.as_view(),name="post_create"),
    url(r'^post/(?P<pk>\d+)/$',views.PostDetailView.as_view(), name="post_detail"),
    url(r'^post/(?P<pk>\d+)/edit/$', views.PostUpdateView.as_view(), name="post_update"),  # in post_detail.html
    url(r'^post/(?P<pk>\d+)/remove/$', views.PostDeleteView.as_view(), name="post_delete"),  # in post_detail.html
    url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name="post_publish"),
    path('drafts/',views.DraftListView.as_view(), name="post_draft_list"),
    ##############
    # path('post/<pk>/comment', views.CommentCreateView.as_view(), name='add_comment_to_post'),
    # url(r'^post/(?P<pk>\d+)/comment/$',views.CommentCreateView.as_view(), name="add_comment_to_post"),
    url(r'^post/(?P<pk>\d+)/comment/$',views.add_comment_to_post, name="add_comment_to_post"),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name="comment_approve"),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name="comment_remove"),

]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.views import LogoutView,LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog.urls', namespace = 'blog')),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(), name="logout")
]

myblog/blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse


# Create your models here.

class Post(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    blog_title = models.CharField(max_length=128)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.blog_title

    def get_absolute_url(self):
        return reverse("blog:post_list")

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)


class Comments(models.Model):
    post = models.ForeignKey('blog.Post', related_name='comments', on_delete=models.CASCADE)
    author = models.CharField(max_length=128)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def __str__(self):
        return self.text

    def get_absolute_url(self):
        return reverse("blog:post_list", kwargs={'pk': self.pk})

    def approve(self):
        self.approved_comment = True
        self.save()

myblog/blog/forms.py
from django import forms
from . models import Post, Comments

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('author', 'blog_title', 'text')

    widgets = {
        'blog_title': forms.TextInput(attrs={'class': 'textinputclass'}),
        'text': forms.Textarea(attrs={'class': 'textinputclass'})
    }


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comments
        fields = ('author','text')

    widgets = {
        'author': forms.TextInput(attrs={'class': 'textinputclass'}),
        'text': forms.Textarea(attrs={'class': 'textinputclass'})
    }

myblog/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, TemplateView, CreateView, DeleteView,DetailView,UpdateView
from . models import Post,Comments
from . forms import PostForm, CommentForm
from django.urls import reverse_lazy
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

class PostListView(ListView):
    model = Post

    def get_queryset(self):
        # return Post.objects.all()
        return Post.objects.filter(published_date__lte=timezone.now())

class AboutView(TemplateView):
    template_name = 'about.html'

class PostCreateView(LoginRequiredMixin,CreateView):
    model = Post
    login_url = '/login/'
    redirect_field_name = 'blog/post_draft_list.html'
    form_class = PostForm

class PostDetailView(DetailView):
    model = Post

class PostUpdateView(LoginRequiredMixin,UpdateView):
    model = Post
    form_class = PostForm
    redirect_field_name = 'blog/post_list.html'
    login_url = '/login/'

class PostDeleteView(LoginRequiredMixin,DeleteView):
    model = Post
    success_url = reverse_lazy("blog:post_list")
    login_url = '/login/'

class DraftListView(LoginRequiredMixin,ListView):
    template_name = 'blog/post_draft_list.html'
    model = Post
    login_url = '/login/'
    redirect_field_name = 'blog/post_draft_list.html'

    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True).order_by('created_date')

@login_required
def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('blog:post_detail', pk=pk)

def add_comment_to_post(request,pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blog:post_detail',pk=post.pk)
    else:
        form = CommentForm()

    return render(request,'blog/comments_form.html',{'form' : form})

@login_required
def comment_approve(req,pk):
    comment = get_object_or_404(Comments, pk=pk)
    comment.approve()
    return redirect('blog:post_detail', pk=comment.post.pk)

@login_required
def comment_remove(req,pk):
    comment = get_object_or_404(Comments,pk=pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect('blog:post_detail', pk=post_pk)

# class CommentCreateView(CreateView):
#     model = Comments
#     form_class = CommentForm
#     redirect_field_name = 'blog/post_detail.html'
#
    # def form_valid(self, form):
    #     form.instance.author = self.request.user
    #     post = Post.objects.get(self.pk)
    #     form.instance.post = post
    #     return super().form_valid(form)
    #
    # def form_valid(self, form):
    #     comment=form.save(commit=False)
    #     comment.post=self.kwargs.get(self.pk)
    #     comment.save()
    #     super().form_valid(form)

myblog/blog/templates/blog/about.html
{% extends "base.html" %}

{% block body_block %}
    <div class="container jumbotron bg-primary">
            <h1>About this company</h1>
            <br>
            <h2>Thanks for checking it out!</h2>
    </div>


{% endblock %}

myblog/blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'blog:post_list' %}">My Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active"><a class="nav-link" href="{% url 'blog:about' %}"> About <span class="sr-only">(current)</span></a></li>
      <li class="nav-item active"><a class="nav-link" href="http://djangoproject.com/"> Django</a></li>
      <li class="nav-item active"><a class="nav-link" href="http://python.org/"> Python</a></li>
    </ul>

  <ul class="navbar-nav mr-auto">
      {% if user.is_authenticated %}
          <li class="nav-item active"><a class="nav-link" href="{% url 'blog:post_create' %}"> New Post </a></li>
          <li class="nav-item active"><a class="nav-link" href="{% url 'blog:post_draft_list' %}"> Drafts </a></li>
          <li class="nav-item active"><a class="nav-link" href="{% url 'logout' %}?next={% url 'blog:post_list' %}"> Logout</a></li>
          <li class="nav-item active mr-3 my-lg-1 text-white"><h4>Welcome : {{user.username}}</h4>
      {% else %}
          <form class="form-inline my-2 my-lg-0" action="{% url 'login' %}">
                <button class="btn btn-primary my-2 my-lg-0" type="submit" hr>Login</button>
          </form>
      {% endif %}
   </ul>

  </div>
</nav>

<br>
{% block body_block %}

{% endblock %}
</body>
</html>

myblog/blog/templates/blog/comments_form.html
{% extends 'base.html' %}

{% block body_block %}

    <div class="container jumbotron">
        <h2>New Comment</h2>
        <form method="post">

            {% csrf_token %}
            {{ form.as_p }}

            <input type="submit" class="btn btn-primary" value="Post comment">

        </form>
    </div>

{% endblock %}

myblog/blog/templates/blog/post_confirm_delete.html
{% extends "base.html" %}

{% block body_block %}

<div class="container jumbotron">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <h2> Are you sure you wanna delete "{{object}}" Post</h2>
        <input type="submit" value="Delete Post" class="btn btn-danger">
    </form>
</div>
{% endblock %}

myblog/blog/templates/blog/post_detail.html
{% extends "base.html" %}

{% block body_block %}

<br>
    <!--Display Posts Details-->
<div class="container jumbotron">
    <h1 class="posttitle loader"> Post : {{post.blog_title}} </h1>

    {% if post.published_date %}
        <p>Published on : {{post.published_date}}</p>
    {% else %}
        <a class="btn btn-primary" href="{% url 'blog:post_publish' pk=post.pk %}">Publish</a>
    {% endif %}

    <br>
    <p>{{post.text|linebreaks}}</p>
    <hr>

    {% if user.is_authenticated %}
        <a class="btn btn-warning" href="{% url 'blog:post_update' pk=post.pk %}">Update</a>
        <a class="btn btn-danger"  href="{% url 'blog:post_delete' pk=post.pk %}">Delete</a>
    {% endif %}

    <hr>

    <a class="btn btn-primary btn-comment" href="{% url 'blog:add_comment_to_post' pk=post.pk %}">Add Comments</a>

    <div class="">
        {% for comment in post.comments.all %}
            <hr>
            {% if user.is_authenticated or comment.approved_comment %}
                <p>{{comment.created_date}}</p>
                {% if not comment.approved_comment %}
                    <a class="" href="{% url 'blog:comment_approve' pk=comment.pk %}"><i class="material-icons" style="color:green">done</i></a>
                    <a class="" href="{% url 'blog:comment_remove' pk=comment.pk %}"><i class="material-icons" style="color:red;">clear</i></a>

                {% endif %}
                <p>{{comment.text}}</p>
                <h6>posted by : {{comment.author}}</h6>
                <hr>
            {% endif %}
        {% empty %}
            <p>No comments</p>
        {% endfor %}
    </div>

</div>


{% endblock %}

myblog/blog/templates/blog/post_draft_list.html
{% extends 'base.html' %}

{% block body_block %}
    <div class=" container jumbotron">

        <h1> List of unpublished Blogs</h1><hr><hr>

        {% for post in post_list %}
        <div class="">
            <h3><a href="{% url 'blog:post_detail' pk=post.pk %}">{{post.blog_title}}</a></h3>
            <h6>Created on : {{post.created_date}} </h6>
        </div>
        <hr>
        {% endfor %}
    </div>
{% endblock %}

myblog/blog/templates/blog/post_form.html
{% extends "base.html" %}

{% block body_block %}

    <div class="container jumbotron" style="background-color: #e3f2fd;">
            <h1>Enter Post Details</h1><br>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Save Post">
        </form>

    </div>


{% endblock %}

myblog/blog/templates/blog/post_list.html
{% extends 'base.html' %}

{% block body_block %}
    <div class=" container jumbotron">
        <h1> List of Published Blogs</h1><hr><hr>

        {% for post in post_list %}
        <div class="posts">
            <h3><a href="{% url 'blog:post_detail' pk=post.pk %}">{{post.blog_title}}</a></h3>
            {% if post.published_date %}
                <h6>Published On : {{post.published_date}}</h6>
            {% else %}
                <h6>Not yet published</h6>
            {% endif %}

            <h5> Comments : {{post.approved_comments.count}}</h5>

        </div>
        <hr>
        {% empty %}
            <h1>Posts not yet created </h1>
        {% endfor %}

    </div>

{% endblock %}